//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleInfoPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleInfoPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ConfirmPursuit {
            get {
                object obj = ResourceManager.GetObject("ConfirmPursuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {&quot;World 1-1&quot;:{&quot;letters&quot;:{&quot;A&quot;:[246,168],&quot;B&quot;:[368,88],&quot;C&quot;:[357,238]}},&quot;World 1-2&quot;:{&quot;letters&quot;:{&quot;A&quot;:[338,104],&quot;B&quot;:[500,84],&quot;C&quot;:[290,217],&quot;D&quot;:[408,295]},&quot;markers&quot;:[{&quot;img&quot;:&quot;client/ammo.png&quot;,&quot;pos&quot;:[265,246],&quot;size&quot;:[18,18]}]},&quot;World 1-3&quot;:{&quot;letters&quot;:{&quot;A&quot;:[293,96],&quot;B&quot;:[242,222],&quot;C&quot;:[396,198],&quot;D&quot;:[490,142],&quot;E&quot;:[338,294],&quot;F&quot;:[463,308],&quot;G&quot;:[628,280]},&quot;markers&quot;:[{&quot;img&quot;:&quot;client/fuel.png&quot;,&quot;pos&quot;:[402,230],&quot;size&quot;:[18,18]},{&quot;img&quot;:&quot;client/fuel.png&quot;,&quot;pos&quot;:[484,176],&quot;size&quot;:[18,18]}]},&quot;World 1-4&quot;:{&quot;letters&quot;:{&quot;A&quot;:[236,85],&quot;B&quot;:[276[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string display_overlay_data {
            get {
                return ResourceManager.GetString("display_overlay_data", resourceCulture);
            }
        }
    }
}
